### ISSUE TITLE
AttributeError: can't set attribute 

### ISSUE THREAD

**Issue by Murphy103** [Souphis/mobile_robot_rl#9]
Hello,I'm running your project and an error occured:

Traceback (most recent call last):
  File "/home/PycharmProjects/gymdemo/mobile_robot_rl/run.py", line 71, in <module>
    run_vision_env(4)
  File "/home/PycharmProjects/gymdemo/mobile_robot_rl/run.py", line 15, in run_vision_env
    length=history_length)
  File "/home/PycharmProjects/gymdemo/mobile_robot_rl/common/env_wrapper.py", line 150, in make_env
    env = FrameStack(env, length, nchw_format)
  File "/home/PycharmProjects/gymdemo/mobile_robot_rl/common/env_wrapper.py", line 104, in __init__
    value.shape = generate_shape(shp)
AttributeError: can't set attribute

Do you know how to solve it？

Thanks in advance :)

**Comment by gbartyzel** [comment]
@Murphy103 Hello, sorry for late answer. I'll look a this in the next month, is it ok for you?
